require("core.plugin_config.colorscheme")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.mason")
require("core.plugin_config.lsp_config")
