[colors]
background       = '#0D0C0C'
black            = '#090618'
blue             = '#7e9cd8'
cursor           = '#C8C093'
cyan             = '#6A9589'
foreground       = '#DCD7BA'
green            = '#76946A'
magenta          = '#957FB8'
red              = '#C34043'
tabs             = '#0D0C0C'
tabs-active      = '#957FB8'
white            = '#C8C093'
yellow           = '#C0A36E'
light-black      = '#727169'
light-blue       = '#7FB4CA'
light-cyan       = '#7AA89F'
light-foreground = '#C8C093'
light-green      = '#98BB6C'
light-magenta    = '#938AA9'
light-red        = '#E82424'
light-white      = '#DCD7BA'
light-yellow     = '#E6C384'
selection-background = '#8BA4B0'
selection-foreground = '#181616'
