[colors]
background       = '#181616'
black            = '#0D0C0C'
blue             = '#8BA4B0'
cursor           = '#C8C093'
cyan             = '#8EA4A2'
foreground       = '#C5C9C5'
green            = '#8a9a7b'
magenta          = '#938AA9'
red              = '#c4746e'
tabs             = '#181616'
tabs-active      = '#938AA9'
white            = '#C8C093'
yellow           = '#c4b28a'
dim-black        = '#0D0C0C'
dim-blue         = '#8BA4B0'
dim-cyan         = '#8EA4A2'
dim-foreground   = '#dfdfd9'
dim-green        = '#06572F'
dim-magenta      = '#938aa9'
dim-red          = '#FF3C3C'
dim-white        = '#EFEFE1'
dim-yellow       = '#E6A003'
light-black      = '#a6a69c'
light-blue       = '#7FB4CA'
light-cyan       = '#7AA89F'
light-foreground = '#C8C093'
light-green      = '#87a987'
light-magenta    = '#938AA9'
light-red        = '#E46876'
light-white      = '#c5c9c5'
light-yellow     = '#E6C384'
selection-background = '#8BA4B0'
selection-foreground = '#181616'
