# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Theme
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="lambda"

# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(git fzf zsh-autosuggestions z)

# Exports
export EDITOR=nvim
export TERM="tmux-256color"
export GPG_TTY=$(tty)

# History
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

HISTSIZE=10000000                # history size
SAVEHIST=10000000                # history save size
DISABLE_AUTO_TITLE="true"        # avoid window rename
KEYTIMEOUT=1                     # remove delay

# Zsh init
source $ZSH/oh-my-zsh.sh

# PATH adds
PATH="$HOME/.local/bin:/usr/local/bin":$PATH
PATH="$HOME/.cargo/bin:$HOME/.cargo/bin/racer":$PATH

# Brew
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

# Aliases
alias vim="nvim"
alias n="nvim"
alias j="z"

# git
alias ga='git add'
alias gc='git commit'
alias gl='git prettylog'
alias gs='git status'
alias gt='git tag'
alias gp='git push'
alias gpl='git pull'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gdiff='git diff'

# clojure
alias clj='rlwrap clojure'
alias lt='lein test'
alias ct='clj -A:test'

# lazygit
alias lg='lazygit'

# datomic
alias start-transactor-dev='~/datomic/datomic-pro-1.0.7187/bin/transactor ~/datomic/datomic-pro-1.0.7187/config/dev-transactor-template.properties'

# deps-new
alias cljn='clojure -Tnew app :name'

# java home
export JAVA_11_HOME=$(/usr/libexec/java_home -v11)
export JAVA_21_HOME=$(/usr/libexec/java_home -v21)
export JAVA_23_HOME=$(/usr/libexec/java_home -v23)
export JAVA_24_HOME=$(/usr/libexec/java_home -v24)

alias java11='export JAVA_HOME=$JAVA_11_HOME'
alias java21='export JAVA_HOME=$JAVA_21_HOME'
alias java23='export JAVA_HOME=$JAVA_23_HOME'
alias java24='export JAVA_HOME="/opt/homebrew/Cellar/openjdk/24.0.2/libexec/openjdk.jdk/Contents/Home"'
alias graalvm24='export JAVA_HOME="/Library/Java/JavaVirtualMachines/graalvm-24.jdk/Contents/Home"'

# default java 21
export JAVA_HOME=$(/usr/libexec/java_home -v21)

# jdklink function to create a symlink for OpenJDK (if not automatically linked)
jdklink() {
  if [ -z "$1" ]; then
    echo "Usage: jdklink <version>"
    return 1
  fi
  sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-"$1".jdk
}

# fnm
# to use on cd it will auto switch node versions based on .nvmrc or .node-version file
# eval "$(fnm env --use-on-cd --shell zsh)"
eval "$(fnm env --shell zsh)"

# work specific configs (git ignored)
[ -f ~/.workrc ] && source ~/.workrc
